# Site settings
title: "Ben Booker, Web Specialist"
description: "Resume for Ben Booker, Web Specialist"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "false"
resume_name: "Ben Booker"
resume_title: "Web Specialist"

# used for the contact button in _layouts/resume.html
resume_contact_email: "bbooker5@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "865-221-6154"
resume_contact_address: "Oak Ridge, TN"

resume_header_contact_info: "Oak Ridge, Tennessee • 865-221-6154 • bbooker5@gmail.com"
display_header_contact_info: "false"

resume_header_intro: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
#  resume_github_url:            "https://github.com/jglovier/resume-template"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/ben-booker-5a2b32144/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://bbooker5.github.io/about/"
#  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
